<?php

/**
 * Deterministic name → Vitasure-inspired theme mapping for organizational grouping only.
 * Keys are category names from DefaultBiomarkerCategoriesSeeder::NAMES (except Overig).
 *
 * Matching: normalized biomarker name equals alias OR contains alias as whole token/substring
 * when alias length >= 4; shorter aliases require token boundary match.
 */
return [
    'Hartgezondheid' => [
        'apob',
        'apo b',
        'lipoproteine (a)',
        'lipoproteïne (a)',
        'lp(a)',
        'ldl',
        'hdl',
        'totaal cholesterol',
        'triglyceriden',
        'non-hdl',
    ],
    'Ontstekingen' => [
        'hscrp',
        'crp hooggevoelig',
        'crp',
        'c-reactief proteïne',
        'c-reactief proteine',
        'witte bloedcel',
        'wbc',
        'leukocyten',
        'neutrofielen',
        'basofielen',
        'eosinofielen',
        'lymfocyten',
        'monocyten',
    ],
    'Cognitie' => [
        'vitamine b12',
        'b12',
        'cobalamine',
        'foliumzuur',
        'folaat',
        'vitamine b9',
    ],
    'Uithoudingsvermogen' => [
        'ferritine',
        'ferritin',
        'hemoglobine',
        'hemoglobin',
        'hematocriet',
        'hct',
        'mcv',
        'mch',
        'mchc',
        'rdw',
        'rbc',
        'rode bloedcel',
        'ijzer',
        'iron',
        'tibc',
        'transferrine',
        'transferrineverzadiging',
        'bloedplaatjes',
        'trombocyten',
        'mpv',
    ],
    'Slaap' => [
        'magnesium',
        'rode bloedcel magnesium',
        'vitamine d',
        'vitamin d',
        'vit d',
        '25-oh vitamine d',
        '25-hydroxyvitamine d',
    ],
    'Hormoonbalans' => [
        'tsh',
        'thyroïd stimulerend hormoon',
        'thyroid stimulating hormone',
        'estradiol',
        'oestradiol',
        'progesteron',
        'cortisol',
        'dheas',
        'dehydroepiandrosterone',
        'calcium',
        'parathormoon',
        'pth',
    ],
    'Metabolisme' => [
        'glucose',
        'glucose nuchter',
        'hba1c',
        'hemoglobine a1c',
        'hemoglobine a1c (ifcc)',
        'hemoglobine a1c (ngsp)',
        'insuline',
        'alt',
        'alanine aminotransferase',
    ],
    'Herstel' => [
        'albumine',
        'ast',
        'aspartaat aminotransferase',
        'ggt',
        'gamma-glutamyl',
        'ck',
        'creatine kinase',
        'kalium',
        'natrium',
        'chloride',
        'bicarbonaat',
    ],
    'Fitness' => [
        'testosteron',
        'vrij testosteron',
        'shbg',
        'geslachtshormoonbindend globuline',
    ],
];
